[env:m5stack-cores3]
platform = espressif32
board = m5stack-cores3
framework = arduino
monitor_speed = 115200
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
board_build.partitions = default_16MB.csv

lib_deps =
    m5stack/M5Unified@^0.2.2

build_flags =
    -DARDUINO_M5STACK_CORES3
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_USE_MALLOC
